export const AppRoutes = {
  default: '/',
  home: '/home',
  cars: '/cars',
  carbooking: '/cars/booking/:id',
  profileSettings: '/profile-settings',
  tripHistory: '/trip-history',
  wallet: '/wallet',
  login: '/login',
  emailConfirmation: '/email/confirm',
  forgotPassword: '/forgot-password',
  resetTokenCheck: '/password/reset/edit',
  passwordReset: '/password-reset',
  hotelsResult: '/hotels',
  hotelInfo: '/hotel/details',
  hotelRooms: '/hotel/rooms',
};
