export const AppRoutes = {
  SIGN_UP: '/',
  HOME: '/home',
  CARS: '/cars',
  CAR_BOOKING: '/cars/booking/:id',
  PROFILE_SETTINGS: '/profile-settings',
  TRIP_HISTORY: '/trip-history',
  WALLET: '/wallet',
  SIGN_IN: '/sign-in',
  EMAIL_CONFIRMATION: '/email/confirm',
  FORGOT_PASSWORD: 'forgot-password',
  RESET_TOKEN_CHECK: '/password/reset/edit',
  PASSWORD_RESET: '/password-reset',
  HOTELS_RESULT: '/hotels',
  ROOM_INFO: '/hotel/room/details',
  HOTEL_ROOMS: '/hotel/rooms',
};
