export const CITIES: string[] = [
  'Київ',
  'Львів',
  'Одеса',
  'Дніпро',
  'Харків',
  'Запоріжжя',
  'Вінниця',
  'Полтава',
  'Черкаси',
  'Чернівці',
  'Івано-Франківськ',
  'Тернопіль',
  'Луцьк',
  'Рівне',
  'Ужгород',
  'Хмельницький',
  'Житомир',
  'Чернігів',
  'Суми',
  'Кропивницький',
  'Миколаїв',
];

export const CITY_MAP: { [key: string]: string } = {
  Київ: 'Kyiv',
  Львів: 'Lviv',
  Одеса: 'Odesa',
  Дніпро: 'Dnipro',
  Харків: 'Kharkiv',
  Запоріжжя: 'Zaporizhzhia',
  Вінниця: 'Vinnytsia',
  Полтава: 'Poltava',
  Черкаси: 'Cherkasy',
  Чернівці: 'Chernivtsi',
  'Івано-Франківськ': 'Ivano-Frankivsk',
  Тернопіль: 'Ternopil',
  Луцьк: 'Lutsk',
  Рівне: 'Rivne',
  Ужгород: 'Uzhhorod',
  Хмельницький: 'Khmelnytskyi',
  Житомир: 'Zhytomyr',
  Чернігів: 'Chernihiv',
  Суми: 'Sumy',
  Кропивницький: 'Kropyvnytskyi',
  Миколаїв: 'Mykolaiv',
};
